//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoHoangNhan_2211110151_DeAnWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEBDB_DOHOANGNHAN_2211110151Entities : DbContext
    {
        public WEBDB_DOHOANGNHAN_2211110151Entities()
            : base("name=WEBDB_DOHOANGNHAN_2211110151Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<TBL_MAKEY> TBL_MAKEY { get; set; }
        public virtual DbSet<TBL_HOADON> TBL_HOADON { get; set; }
        public virtual DbSet<TBL_HOADON_CHITIET> TBL_HOADON_CHITIET { get; set; }
        public virtual DbSet<TBL_LOAISANPHAM> TBL_LOAISANPHAM { get; set; }
        public virtual DbSet<TBL_SANPHAM> TBL_SANPHAM { get; set; }
    }
}
