//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoHoangNhan_2211110151_DeAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SANPHAM
    {
        public int IDSP { get; set; }
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public double GIATIEN { get; set; }
        public Nullable<double> GIACU { get; set; }
        public Nullable<int> SO_LUONG_TON_TRONG_KHO { get; set; }
        public string HINH_DAI_DIEN { get; set; }
        public string HINH_CHI_TIET_1 { get; set; }
        public string HINH_CHI_TIET_2 { get; set; }
        public string HINH_CHI_TIET_3 { get; set; }
        public string HINH_CHI_TIET_4 { get; set; }
        public Nullable<int> IDLOAI { get; set; }
        public string NOIDUNG_MOTA_SANPHAM { get; set; }
        public Nullable<int> THANG { get; set; }
    
        public virtual TBL_LOAISANPHAM TBL_LOAISANPHAM { get; set; }

        public string MAKEY { get; set; }
    }
}
