//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoHoangNhan_2211110151_DeAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOAISANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_LOAISANPHAM()
        {
            this.TBL_SANPHAM = new HashSet<TBL_SANPHAM>();
        }
    
        public int IDLOAI { get; set; }
        public string TENLOAI { get; set; }
        public string HINHANH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SANPHAM> TBL_SANPHAM { get; set; }
    }
}
