//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoHoangNhan_2211110151_DeAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MAKEY
    {
        public int ID { get; set; }
        public string MASP { get; set; }
        public string MAKEY { get; set; }
        public Nullable<bool> IS_USED { get; set; }
    }
}
